### Create user

POST http://localhost:9000/user
Content-Type: application/json

{
  "email": "example12345678910@example.com",
  "password": {
    "password": "ValidPass123"
  }
}


###Delet

POST http://localhost:9000/post
Content-Type: application/json

{
  "authorId": 1,
  "title": "was deleted",
  "content": "This is the content of my first post."
}

###Delet by id

DELETE http://localhost:9000/post/35

### Get By Id

GET http://localhost:9000/post/23

### Get limit post
GET http://localhost:9000/post/1/posts?page=1&size=10